package com.dovecot.dcmc_utils;

import com.dovecot.dcmc_utils.config.DCUConfig;
import com.dovecot.dcmc_utils.utils.CfgHandler;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.weather.LightningStrikeEvent;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.logging.Logger;

public class DoveCotMCUtilities extends JavaPlugin implements Listener {

    public static Logger LOGGER = Bukkit.getLogger();
    public FileConfiguration config = this.getConfig();

    @Override
    public void onEnable() {
        getLogger().info(ChatColor.GREEN + "Enabled " + this.getName());

        DCUConfig.initialize(this);

        getServer().getPluginManager().registerEvents(this, this);
    }

    @Override
    public void onDisable() {
        getLogger().info(ChatColor.RED + "Disabled " + this.getName());
    }

    @EventHandler
    public void onPlayerJoinEvent(PlayerJoinEvent event){
        if(config.getBoolean("casts tip(s) on player join")){
            final Player player = event.getPlayer();
            final String messageToSend = CfgHandler.getStringOrEmpty(config, "tip content");
            player.sendMessage(messageToSend);
        }
    }

    @EventHandler
    public void onLightningStrikeEvent(LightningStrikeEvent event){
        event.setCancelled(config.getBoolean("prevents lightning generation"));
        if (event.getCause() == LightningStrikeEvent.Cause.COMMAND || event.getCause() == LightningStrikeEvent.Cause.UNKNOWN && config.getBoolean("notify when someone tries to generate a lightning bolt")){
            Bukkit.broadcastMessage(CfgHandler.getStringOrEmpty(config, "lightning bolt interception notification content"));
            LOGGER.info("A bolt to be generated by command has been intercepted :)");
        }
    }
}
