package com.dovecot.dcmc_utils.tools.event_listeners;

import com.dovecot.dcmc_utils.config.DCUConfig;
import com.dovecot.dcmc_utils.utils.CfgHandler;
import org.bukkit.Bukkit;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.event.weather.LightningStrikeEvent;

import java.util.logging.Logger;

public class LightningStrike {
    public static void preventLightnings(LightningStrikeEvent event, FileConfiguration config, Logger logger){
        event.setCancelled(config.getBoolean(DCUConfig.ANTI_LIGHTNING));
        if ((event.getCause() == LightningStrikeEvent.Cause.COMMAND || event.getCause() == LightningStrikeEvent.Cause.UNKNOWN)
                && config.getBoolean(DCUConfig.ANTI_LIGHTNING_NOTIFY)){
            Bukkit.broadcastMessage(CfgHandler.getStringOrEmpty(config, DCUConfig.ANTI_LIGHTNING_NOTIFICATION_CONTENT));
            logger.info("A bolt to be generated by command has been intercepted :)");
        }
    }
}
